[2022-05-19 00:09:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:09:15] [WARNING]: 群消息发送失败: 信息为空. 
[2022-05-19 00:09:31] [WARNING]: 群消息发送失败: 信息为空. 
[2022-05-19 00:14:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:15:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:16:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:16:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1367,"PacketSent":1111,"PacketLost":0,"MessageReceived":167,"MessageSent":68,"LastMessageTime":1652890581,"DisconnectTimes":0,"LostTimes":0}},"time":1652890610}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:17] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"香啊","message_id":731287610,"message_seq":197851,"message_type":"group","post_type":"message","raw_message":"香啊","self_id":2945339871,"sender":{"age":0,"area":"","card":"↑二五仔","level":"","nickname":"小嘴抹了蜜","role":"admin","sex":"unknown","title":"爸爸","user_id":1018460089},"sub_type":"normal","time":1652890625,"user_id":1018460089}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:17] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1367,"PacketSent":1111,"PacketLost":0,"MessageReceived":167,"MessageSent":68,"LastMessageTime":1652890581,"DisconnectTimes":0,"LostTimes":0}},"time":1652890624}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:23] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:31] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1369,"PacketSent":1112,"PacketLost":0,"MessageReceived":168,"MessageSent":68,"LastMessageTime":1652890624,"DisconnectTimes":0,"LostTimes":0}},"time":1652890637}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:45] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1369,"PacketSent":1112,"PacketLost":0,"MessageReceived":168,"MessageSent":68,"LastMessageTime":1652890624,"DisconnectTimes":0,"LostTimes":0}},"time":1652890651}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:49] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:51] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"#学习 #魔怔模式 丁真 纯，太纯了","message_id":-1298153088,"message_seq":197852,"message_type":"group","post_type":"message","raw_message":"#学习 #魔怔模式 丁真 纯，太纯了","self_id":2945339871,"sender":{"age":0,"area":"","card":"↑二五仔","level":"","nickname":"小嘴抹了蜜","role":"admin","sex":"unknown","title":"爸爸","user_id":1018460089},"sub_type":"normal","time":1652890658,"user_id":1018460089}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:17:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:17:53] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:17:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:17:59] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1371,"PacketSent":1113,"PacketLost":0,"MessageReceived":169,"MessageSent":68,"LastMessageTime":1652890657,"DisconnectTimes":0,"LostTimes":0}},"time":1652890665}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:20:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:20:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:20:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:22:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:23:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:23:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:24:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:24:53] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 00:25:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 00:25:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 00:25:13] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"#学习 #魔怔模式 香啊|白发 香啊，很香啊|戳啦，极霸毛啦","message_id":-1500995033,"message_seq":626,"message_type":"group","post_type":"message","raw_message":"#学习 #魔怔模式 香啊|白发 香啊，很香啊|戳啦，极霸毛啦","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652891090,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 00:26:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": EOF 将进行第 1 次重试 
[2022-05-19 00:26:04] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:11] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1643,"PacketSent":1250,"PacketLost":0,"MessageReceived":190,"MessageSent":183,"LastMessageTime":1652891153,"DisconnectTimes":0,"LostTimes":0}},"time":1652891160}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:17] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:18] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:25] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1732,"PacketSent":1294,"PacketLost":0,"MessageReceived":190,"MessageSent":227,"LastMessageTime":1652891153,"DisconnectTimes":0,"LostTimes":0}},"time":1652891171}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:28] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"宛如数据库被攻击了","message_id":-2136366334,"message_seq":197872,"message_type":"group","post_type":"message","raw_message":"宛如数据库被攻击了","self_id":2945339871,"sender":{"age":0,"area":"","card":"(ᗜ ˰ ᗜ)​","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"admin","sex":"unknown","title":"爸爸","user_id":308006378},"sub_type":"normal","time":1652891176,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1733,"PacketSent":1294,"PacketLost":0,"MessageReceived":191,"MessageSent":227,"LastMessageTime":1652891175,"DisconnectTimes":0,"LostTimes":0}},"time":1652891185}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:44] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"[CQ:image,file=556e3fce47db767441ea28d4044da80e.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/588696648-2295194401-556E3FCE47DB767441EA28D4044DA80E/0?term=3,subType=0][CQ:image,file=7b40f0a162db162766e0f595866748e7.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/588696648-2171293527-7B40F0A162DB162766E0F595866748E7/0?term=3,subType=0]","message_id":-139553900,"message_seq":197873,"message_type":"group","post_type":"message","raw_message":"[CQ:image,file=556e3fce47db767441ea28d4044da80e.image,subType=0][CQ:image,file=7b40f0a162db162766e0f595866748e7.image,subType=0]","self_id":2945339871,"sender":{"age":0,"area":"","card":"(ᗜ ˰ ᗜ)​","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"admin","sex":"unknown","title":"爸爸","user_id":308006378},"sub_type":"normal","time":1652891190,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:26:48] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"塞了200条数据进去草","message_id":1774847543,"message_seq":197874,"message_type":"group","post_type":"message","raw_message":"塞了200条数据进去草","self_id":2945339871,"sender":{"age":0,"area":"","card":"(ᗜ ˰ ᗜ)​","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"admin","sex":"unknown","title":"爸爸","user_id":308006378},"sub_type":"normal","time":1652891196,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:49] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:26:53] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1736,"PacketSent":1295,"PacketLost":0,"MessageReceived":193,"MessageSent":227,"LastMessageTime":1652891195,"DisconnectTimes":0,"LostTimes":0}},"time":1652891199}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:26:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:26:59] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:27:03] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:27:06] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1736,"PacketSent":1295,"PacketLost":0,"MessageReceived":193,"MessageSent":227,"LastMessageTime":1652891195,"DisconnectTimes":0,"LostTimes":0}},"time":1652891213}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:27:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:27:13] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:27:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:27:20] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1737,"PacketSent":1296,"PacketLost":0,"MessageReceived":193,"MessageSent":227,"LastMessageTime":1652891195,"DisconnectTimes":0,"LostTimes":0}},"time":1652891226}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:27:23] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:27:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:27:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:27:34] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1737,"PacketSent":1296,"PacketLost":0,"MessageReceived":193,"MessageSent":227,"LastMessageTime":1652891195,"DisconnectTimes":0,"LostTimes":0}},"time":1652891240}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:27:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:27:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:27:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:27:48] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":1737,"PacketSent":1296,"PacketLost":0,"MessageReceived":193,"MessageSent":227,"LastMessageTime":1652891195,"DisconnectTimes":0,"LostTimes":0}},"time":1652891254}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 00:27:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 00:27:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 00:27:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 00:31:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 01:09:17] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 05:00:43] [ERROR]: Protocol -> unexpected disconnect: read tcp 192.168.31.9:2631->109.244.153.11:8080: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
[2022-05-19 05:01:04] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 123.125.0.217:14000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
[2022-05-19 05:01:04] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 123.125.0.217:14000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
[2022-05-19 05:01:04] [WARNING]: Bot已离线: connection dropped by server. 
[2022-05-19 05:01:07] [WARNING]: 将在 3 秒后尝试重连. 重连次数：2/0 
[2022-05-19 05:01:10] [WARNING]: 尝试重连... 
[2022-05-19 10:22:00] [ERROR]: Protocol -> unexpected disconnect: EOF 
[2022-05-19 10:32:31] [ERROR]: Protocol -> unexpected disconnect: EOF 
[2022-05-19 11:29:42] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:30:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:30:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:30:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:30:24] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3398,"PacketSent":2863,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931010}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:30:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:30:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:30:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:30:37] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3400,"PacketSent":2865,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931024}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:30:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:30:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:30:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:30:51] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3400,"PacketSent":2865,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931037}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:30:53] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:30:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:31:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:31:05] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3401,"PacketSent":2866,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931051}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:31:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:31:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:31:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:31:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3401,"PacketSent":2866,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931065}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:31:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:31:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:31:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:31:32] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3402,"PacketSent":2867,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931079}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:31:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:31:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:31:42] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:31:46] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3402,"PacketSent":2867,"PacketLost":0,"MessageReceived":247,"MessageSent":258,"LastMessageTime":1652931000,"DisconnectTimes":3,"LostTimes":0}},"time":1652931092}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:31:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:31:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:32:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:32:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:32:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:32:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:32:59] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3412,"PacketSent":2875,"PacketLost":0,"MessageReceived":249,"MessageSent":258,"LastMessageTime":1652931154,"DisconnectTimes":3,"LostTimes":0}},"time":1652931165}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:33:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:33:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:33:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:33:12] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3413,"PacketSent":2876,"PacketLost":0,"MessageReceived":249,"MessageSent":258,"LastMessageTime":1652931154,"DisconnectTimes":3,"LostTimes":0}},"time":1652931179}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:33:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:33:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:33:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:33:26] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3413,"PacketSent":2876,"PacketLost":0,"MessageReceived":249,"MessageSent":258,"LastMessageTime":1652931154,"DisconnectTimes":3,"LostTimes":0}},"time":1652931192}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:33:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:33:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:33:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:33:40] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3414,"PacketSent":2877,"PacketLost":0,"MessageReceived":249,"MessageSent":258,"LastMessageTime":1652931154,"DisconnectTimes":3,"LostTimes":0}},"time":1652931206}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:34:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:34:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:34:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:34:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3419,"PacketSent":2881,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931245}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:34:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:34:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:34:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:34:32] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3420,"PacketSent":2882,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931259}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:34:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:34:38] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:34:42] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:34:46] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3420,"PacketSent":2882,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931272}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:34:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:34:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:34:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:35:00] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3421,"PacketSent":2883,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931286}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:35:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:35:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:35:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:35:14] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3421,"PacketSent":2883,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931300}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:35:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:35:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:35:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:35:27] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3422,"PacketSent":2884,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931314}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:35:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:35:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:35:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:35:41] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3422,"PacketSent":2884,"PacketLost":0,"MessageReceived":250,"MessageSent":258,"LastMessageTime":1652931233,"DisconnectTimes":3,"LostTimes":0}},"time":1652931327}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:38:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:38:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:38:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:38:59] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3434,"PacketSent":2894,"PacketLost":0,"MessageReceived":252,"MessageSent":258,"LastMessageTime":1652931505,"DisconnectTimes":3,"LostTimes":0}},"time":1652931525}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:39:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:39:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:39:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:39:12] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3434,"PacketSent":2894,"PacketLost":0,"MessageReceived":252,"MessageSent":258,"LastMessageTime":1652931505,"DisconnectTimes":3,"LostTimes":0}},"time":1652931539}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:39:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:39:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:40:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:40:04] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:40:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:40:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:40:13] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:40:17] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"#学习","message_id":-1431277321,"message_seq":794,"message_type":"group","post_type":"message","raw_message":"#学习","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652931594,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:40:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:40:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:40:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:40:34] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3438,"PacketSent":2897,"PacketLost":0,"MessageReceived":253,"MessageSent":258,"LastMessageTime":1652931592,"DisconnectTimes":3,"LostTimes":0}},"time":1652931620}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:41:17] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:41:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:41:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:41:29] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3450,"PacketSent":2906,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931675}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:41:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:41:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:41:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:41:42] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3450,"PacketSent":2906,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931689}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:41:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:41:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:41:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:41:56] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3450,"PacketSent":2906,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931702}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:41:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:42:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:42:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:42:10] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3451,"PacketSent":2907,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931716}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:42:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:42:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:42:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:42:24] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3451,"PacketSent":2907,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931730}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:42:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:42:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:42:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:42:37] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3452,"PacketSent":2908,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931744}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:42:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:42:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:42:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:42:51] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3452,"PacketSent":2908,"PacketLost":0,"MessageReceived":255,"MessageSent":259,"LastMessageTime":1652931653,"DisconnectTimes":3,"LostTimes":0}},"time":1652931757}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:42:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:42:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:43:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:43:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:43:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:43:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:43:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:43:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:43:38] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"Test","message_id":867770701,"message_seq":797,"message_type":"group","post_type":"message","raw_message":"Test","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652931795,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:43:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3455,"PacketSent":2910,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931795}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:43:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:43:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:43:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:44:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3455,"PacketSent":2910,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931819}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:44:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:44:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:44:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:44:29] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3456,"PacketSent":2911,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931844}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:44:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:44:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:44:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:44:53] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3458,"PacketSent":2913,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931869}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:44:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:45:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:45:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:45:18] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3459,"PacketSent":2914,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931893}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:45:23] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:45:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:45:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:45:42] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3460,"PacketSent":2915,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931918}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:45:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:45:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:46:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:46:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:46:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:46:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:46:49] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3462,"PacketSent":2917,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652931995}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:46:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:46:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:46:59] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:47:02] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3463,"PacketSent":2918,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652932009}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:47:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:47:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:47:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:47:16] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3463,"PacketSent":2918,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652932022}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:47:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:47:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:47:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:47:30] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3464,"PacketSent":2919,"PacketLost":0,"MessageReceived":256,"MessageSent":259,"LastMessageTime":1652931794,"DisconnectTimes":3,"LostTimes":0}},"time":1652932036}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:47:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:47:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:47:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:48:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:48:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:48:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:48:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:48:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:48:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:48:39] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"Test","message_id":-738128822,"message_seq":799,"message_type":"group","post_type":"message","raw_message":"Test","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652932096,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:48:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3469,"PacketSent":2922,"PacketLost":0,"MessageReceived":258,"MessageSent":259,"LastMessageTime":1652932095,"DisconnectTimes":3,"LostTimes":0}},"time":1652932095}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:48:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:48:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:48:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:49:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3469,"PacketSent":2922,"PacketLost":0,"MessageReceived":258,"MessageSent":259,"LastMessageTime":1652932095,"DisconnectTimes":3,"LostTimes":0}},"time":1652932119}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:49:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:49:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:49:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:49:28] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3470,"PacketSent":2923,"PacketLost":0,"MessageReceived":258,"MessageSent":259,"LastMessageTime":1652932095,"DisconnectTimes":3,"LostTimes":0}},"time":1652932144}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:49:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:49:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:49:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:49:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:50:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:50:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:50:09] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3473,"PacketSent":2925,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932195}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:50:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:50:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:50:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:50:22] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3473,"PacketSent":2925,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932209}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:50:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:50:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:50:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:50:36] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3474,"PacketSent":2926,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932222}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:50:38] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:50:42] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:50:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:50:50] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3474,"PacketSent":2926,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932236}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:50:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:50:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:51:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:51:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3475,"PacketSent":2927,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932250}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:51:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:51:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:51:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:51:17] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3475,"PacketSent":2927,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932264}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:51:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:51:23] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:51:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:51:31] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3477,"PacketSent":2929,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932277}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:51:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:51:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:51:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:51:45] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3477,"PacketSent":2929,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932291}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:51:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:51:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:51:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:51:59] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3478,"PacketSent":2930,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932305}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:52:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:52:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:52:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:52:13] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3478,"PacketSent":2930,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932319}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:52:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:52:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:52:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:52:26] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3478,"PacketSent":2930,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932333}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:52:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:52:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:52:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:52:40] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3479,"PacketSent":2931,"PacketLost":0,"MessageReceived":259,"MessageSent":259,"LastMessageTime":1652932182,"DisconnectTimes":3,"LostTimes":0}},"time":1652932346}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:52:49] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:52:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 11:52:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:52:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 11:53:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:53:03] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 11:53:09] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"Test","message_id":4487180,"message_seq":801,"message_type":"group","post_type":"message","raw_message":"Test","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652932366,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:53:09] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3480,"PacketSent":2931,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932365}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 11:53:17] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:53:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:53:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:53:29] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3481,"PacketSent":2932,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932395}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:53:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:53:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:53:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:53:42] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3482,"PacketSent":2933,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932409}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:53:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:53:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:53:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:53:56] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3482,"PacketSent":2933,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932422}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:53:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:54:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:54:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:54:10] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3483,"PacketSent":2934,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932436}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:54:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:54:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:54:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:54:24] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3483,"PacketSent":2934,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932450}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:54:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:54:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:54:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:54:37] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3484,"PacketSent":2935,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932464}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:54:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:54:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:54:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:54:51] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3484,"PacketSent":2935,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932477}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:54:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:54:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:55:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:55:05] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3486,"PacketSent":2937,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932491}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:55:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:55:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:55:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:55:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3486,"PacketSent":2937,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932505}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:55:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:55:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:55:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:55:33] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3487,"PacketSent":2938,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932519}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:55:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:55:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:55:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:55:46] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3487,"PacketSent":2938,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932533}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:55:49] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:55:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:55:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:56:00] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3488,"PacketSent":2939,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932546}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:56:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:56:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:56:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:56:14] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3488,"PacketSent":2939,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932560}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:56:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:56:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:56:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:56:28] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3488,"PacketSent":2939,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932574}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:56:30] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:56:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:56:38] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:56:41] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3489,"PacketSent":2940,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932588}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:56:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:56:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:56:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:56:55] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3489,"PacketSent":2940,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932601}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:56:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:57:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:57:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:57:09] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3490,"PacketSent":2941,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932615}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:57:11] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:57:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:57:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:57:23] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3490,"PacketSent":2941,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932629}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:57:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:57:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:57:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:57:36] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3491,"PacketSent":2942,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932643}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:57:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:57:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:57:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:57:50] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3491,"PacketSent":2942,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932656}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:57:53] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:57:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:58:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:58:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3492,"PacketSent":2943,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932670}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:58:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:58:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:58:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:58:18] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3492,"PacketSent":2943,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932684}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:58:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:58:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:58:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:58:31] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3494,"PacketSent":2945,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932698}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:58:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:58:38] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:58:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:58:45] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3494,"PacketSent":2945,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932711}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:58:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:58:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:58:55] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:58:59] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3494,"PacketSent":2945,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932725}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:59:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:59:05] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:59:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:59:13] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3495,"PacketSent":2946,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932739}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:59:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:59:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:59:23] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:59:26] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3495,"PacketSent":2946,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932753}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:59:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:59:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:59:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:59:40] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3496,"PacketSent":2947,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932766}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:59:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 11:59:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 11:59:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 11:59:54] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3496,"PacketSent":2947,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932780}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 11:59:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:00:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:00:04] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:00:08] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3497,"PacketSent":2948,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932794}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:00:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:00:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:00:18] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:00:22] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3497,"PacketSent":2948,"PacketLost":0,"MessageReceived":260,"MessageSent":259,"LastMessageTime":1652932364,"DisconnectTimes":3,"LostTimes":0}},"time":1652932808}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:00:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:00:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 12:00:40] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 12:00:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 12:00:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 12:00:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": EOF 将进行第 3 次重试 
[2022-05-19 12:00:52] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3499,"PacketSent":2949,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932835}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:00:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:00:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:01:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:01:06] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3500,"PacketSent":2950,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932852}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:01:08] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:01:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:01:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:01:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3500,"PacketSent":2950,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932866}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:01:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:01:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:01:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:01:33] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3501,"PacketSent":2951,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932879}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:01:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:01:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:01:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:01:47] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3501,"PacketSent":2951,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932893}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:01:49] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:01:53] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:01:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:02:01] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3503,"PacketSent":2953,"PacketLost":0,"MessageReceived":261,"MessageSent":259,"LastMessageTime":1652932831,"DisconnectTimes":3,"LostTimes":0}},"time":1652932907}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 12:02:03] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 12:02:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 12:02:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 12:19:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:13:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:13:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:13:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:13:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:13:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:13:46] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"升天","message_id":846338702,"message_seq":821,"message_type":"group","post_type":"message","raw_message":"升天","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652937203,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:13:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:14:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:14:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:14:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:14:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:14:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:14:33] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:14:38] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"升天","message_id":-595821662,"message_seq":823,"message_type":"group","post_type":"message","raw_message":"升天","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652937255,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:14:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3716,"PacketSent":3131,"PacketLost":0,"MessageReceived":287,"MessageSent":268,"LastMessageTime":1652937254,"DisconnectTimes":3,"LostTimes":0}},"time":1652937255}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:14:44] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:14:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:15:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:15:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:15:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:15:20] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:15:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 13:15:35] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:15:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:15:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:15:48] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:15:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:15:54] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"升天","message_id":891281047,"message_seq":825,"message_type":"group","post_type":"message","raw_message":"升天","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652937331,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:15:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:16:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3722,"PacketSent":3135,"PacketLost":0,"MessageReceived":289,"MessageSent":268,"LastMessageTime":1652937330,"DisconnectTimes":3,"LostTimes":0}},"time":1652937340}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:16:09] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:16:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:16:25] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:16:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:16:38] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:16:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:16:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:17:03] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:17:09] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3724,"PacketSent":3137,"PacketLost":0,"MessageReceived":289,"MessageSent":268,"LastMessageTime":1652937330,"DisconnectTimes":3,"LostTimes":0}},"time":1652937405}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:17:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:17:21] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:17:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:17:34] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3725,"PacketSent":3138,"PacketLost":0,"MessageReceived":289,"MessageSent":268,"LastMessageTime":1652937330,"DisconnectTimes":3,"LostTimes":0}},"time":1652937429}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:17:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:17:45] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:17:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:17:58] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3726,"PacketSent":3139,"PacketLost":0,"MessageReceived":289,"MessageSent":268,"LastMessageTime":1652937330,"DisconnectTimes":3,"LostTimes":0}},"time":1652937454}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:18:03] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:18:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:18:16] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:18:23] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":3727,"PacketSent":3140,"PacketLost":0,"MessageReceived":289,"MessageSent":268,"LastMessageTime":1652937330,"DisconnectTimes":3,"LostTimes":0}},"time":1652937478}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 13:18:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 13:18:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 13:18:41] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 13:18:47] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:18:51] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 13:39:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:40:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:46:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:55:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:57:27] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 13:57:31] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 13:59:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 14:16:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 14:16:59] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 15:32:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 15:32:43] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 15:32:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 15:32:50] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4792,"PacketSent":3724,"PacketLost":0,"MessageReceived":574,"MessageSent":462,"LastMessageTime":1652945031,"DisconnectTimes":3,"LostTimes":0}},"time":1652945556}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 15:32:52] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 15:32:57] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 15:33:01] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 15:33:05] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4793,"PacketSent":3725,"PacketLost":0,"MessageReceived":574,"MessageSent":462,"LastMessageTime":1652945031,"DisconnectTimes":3,"LostTimes":0}},"time":1652945570}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 15:33:07] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 15:33:12] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 15:33:15] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 15:33:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4793,"PacketSent":3725,"PacketLost":0,"MessageReceived":574,"MessageSent":462,"LastMessageTime":1652945031,"DisconnectTimes":3,"LostTimes":0}},"time":1652945585}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-19 15:33:22] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-19 15:33:26] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-19 15:33:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-19 16:44:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-05-19 16:44:13] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-05-19 16:44:19] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-05-19 16:44:26] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":869735393,"message":"#学习 #全局 #色图 [CQ:image,file=5d331e771f8a5a66aa80e0128383ef4a.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/869735393-3163863897-5D331E771F8A5A66AA80E0128383EF4A/0?term=3,subType=0]and[CQ:image,file=3103500396d96ec876576c3ae9b2b413.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/869735393-2516197483-3103500396D96EC876576C3AE9B2B413/0?term=3,subType=0]and[CQ:image,file=bd9dd7a3ed4357ac3ecaa003e1080339.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/869735393-2775109799-BD9DD7A3ED4357AC3ECAA003E1080339/0?term=3,subType=0]and[CQ:image,file=39f668177000b6d649809028ba55e2fc.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/869735393-2437843654-39F668177000B6D649809028BA55E2FC/0?term=3,subType=0]and[CQ:image,file=a2f1794c8b6c4230868f32e881aade8c.image,url=https://gchat.qpic.cn/gchatpic_new/308006378/869735393-2882624273-A2F1794C8B6C4230868F32E881AADE8C/0?term=3,subType=0]","message_id":-577924710,"message_seq":1121,"message_type":"group","post_type":"message","raw_message":"#学习 #全局 #色图 [CQ:image,file=5d331e771f8a5a66aa80e0128383ef4a.image,subType=0]and[CQ:image,file=3103500396d96ec876576c3ae9b2b413.image,subType=0]and[CQ:image,file=bd9dd7a3ed4357ac3ecaa003e1080339.image,subType=0]and[CQ:image,file=39f668177000b6d649809028ba55e2fc.image,subType=0]and[CQ:image,file=a2f1794c8b6c4230868f32e881aade8c.image,subType=0]","self_id":2945339871,"sender":{"age":0,"area":"","card":"","level":"","nickname":"(ᗜ ˰ ᗜ)​","role":"owner","sex":"unknown","title":"","user_id":308006378},"sub_type":"normal","time":1652949840,"user_id":308006378}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-05-19 21:47:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": read tcp [::1]:11431->[::1]:8400: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 1 次重试 
